const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Pin,
		C3.Plugins.NinePatch,
		C3.Plugins.TiledBg,
		C3.Behaviors.EightDir,
		C3.Plugins.Mouse,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.TiledBg.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.TiledBg.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.NinePatch.Cnds.IsOnScreen,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.TiledBg.Acts.SetBoolInstanceVar,
		C3.Plugins.TiledBg.Acts.ZMoveToObject,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.NinePatch.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Browser.Acts.Alert,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.NinePatch.Acts.SetY,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.Mouse.Acts.SetCursorSprite,
		C3.Plugins.TiledBg.Cnds.IsOnScreen,
		C3.Plugins.TiledBg.Cnds.CompareY,
		C3.Plugins.TiledBg.Acts.SetY,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Mouse.Cnds.OnClick
	];
};
self.C3_JsPropNameTable = [
	{Pin: 0},
	{Exit: 0},
	{creditosbutton: 0},
	{nivelesbutton: 0},
	{jugarbutton: 0},
	{backmenu: 0},
	{"8Direction": 0},
	{numeros1: 0},
	{numeros2: 0},
	{Logo: 0},
	{rightleft: 0},
	{menuprincipal: 0},
	{niveles: 0},
	{atras: 0},
	{creidtsmenu: 0},
	{Right: 0},
	{Left: 0},
	{Up: 0},
	{Down: 0},
	{InitialX: 0},
	{InitialY: 0},
	{pressbutton: 0},
	{win: 0},
	{player: 0},
	{ventanadecomandos: 0},
	{agregarderecha: 0},
	{comandoderecha: 0},
	{spawner: 0},
	{contenedordecomandos: 0},
	{Mouse: 0},
	{Browser: 0},
	{comandoizquierda: 0},
	{agregarizquierda: 0},
	{comandoarriba: 0},
	{agregararriba: 0},
	{agregarabajo: 0},
	{comandoabajo: 0},
	{play: 0},
	{lastactionx: 0},
	{lasactiony: 0},
	{detector: 0},
	{barrera1: 0},
	{derechadetect: 0},
	{izquierdadetect: 0},
	{arribadetect: 0},
	{abajodetect: 0},
	{barrera2: 0},
	{ventanadecomandosback: 0},
	{Restart: 0},
	{menu: 0},
	{menucuadro: 0},
	{botonesmenu: 0},
	{backcomun: 0},
	{limit: 0},
	{rightbuttonsback: 0},
	{soundbutton: 0},
	{agregarinteractuar: 0},
	{comandointeractuar: 0},
	{interaccion: 0},
	{buttonblue: 0},
	{open: 0},
	{doorblue: 0},
	{SubXCommands: 0},
	{SubYCommands: 0},
	{AuxXCommands: 0},
	{AuxYCommands: 0},
	{contienexysub: 0},
	{ventanadecomandossub: 0},
	{executed: 0},
	{comandoiralasub: 0},
	{agregarsub: 0},
	{startsub: 0},
	{endsub: 0},
	{ventanadecomandossubback: 0},
	{selectorprincipal: 0},
	{selectorsub: 0},
	{Spin: 0},
	{SpinBloolean: 0},
	{wintp: 0},
	{buttonred: 0},
	{doorred: 0},
	{doorgreen: 0},
	{buttongreen: 0},
	{dooryellow: 0},
	{buttonyellow: 0},
	{scale: 0},
	{xdirection: 0},
	{xboolean: 0},
	{copa: 0},
	{Audio: 0},
	{tutoriales: 0},
	{clicktocontinue: 0},
	{cursor: 0},
	{welcome: 0},
	{Sounds: 0},
	{NivelActual: 0},
	{XCommands: 0},
	{YCommands: 0}
];

self.InstanceType = {
	Exit: class extends self.ISpriteInstance {},
	creditosbutton: class extends self.ISpriteInstance {},
	nivelesbutton: class extends self.ISpriteInstance {},
	jugarbutton: class extends self.ISpriteInstance {},
	backmenu: class extends self.IWorldInstance {},
	numeros1: class extends self.ITiledBackgroundInstance {},
	numeros2: class extends self.ITiledBackgroundInstance {},
	Logo: class extends self.ISpriteInstance {},
	menuprincipal: class extends self.ITiledBackgroundInstance {},
	niveles: class extends self.ISpriteInstance {},
	atras: class extends self.ISpriteInstance {},
	creidtsmenu: class extends self.ISpriteInstance {},
	player: class extends self.ISpriteInstance {},
	ventanadecomandos: class extends self.ITiledBackgroundInstance {},
	agregarderecha: class extends self.ISpriteInstance {},
	comandoderecha: class extends self.ISpriteInstance {},
	spawner: class extends self.ISpriteInstance {},
	contenedordecomandos: class extends self.ITiledBackgroundInstance {},
	Mouse: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	comandoizquierda: class extends self.ISpriteInstance {},
	agregarizquierda: class extends self.ISpriteInstance {},
	comandoarriba: class extends self.ISpriteInstance {},
	agregararriba: class extends self.ISpriteInstance {},
	agregarabajo: class extends self.ISpriteInstance {},
	comandoabajo: class extends self.ISpriteInstance {},
	detector: class extends self.ISpriteInstance {},
	barrera1: class extends self.ITiledBackgroundInstance {},
	derechadetect: class extends self.ISpriteInstance {},
	play: class extends self.ISpriteInstance {},
	izquierdadetect: class extends self.ISpriteInstance {},
	arribadetect: class extends self.ISpriteInstance {},
	abajodetect: class extends self.ISpriteInstance {},
	barrera2: class extends self.ISpriteInstance {},
	ventanadecomandosback: class extends self.ITiledBackgroundInstance {},
	Restart: class extends self.ISpriteInstance {},
	menu: class extends self.ISpriteInstance {},
	menucuadro: class extends self.IWorldInstance {},
	botonesmenu: class extends self.ISpriteInstance {},
	backcomun: class extends self.ITiledBackgroundInstance {},
	limit: class extends self.ISpriteInstance {},
	rightbuttonsback: class extends self.ITiledBackgroundInstance {},
	soundbutton: class extends self.ISpriteInstance {},
	agregarinteractuar: class extends self.ISpriteInstance {},
	comandointeractuar: class extends self.ISpriteInstance {},
	interaccion: class extends self.ISpriteInstance {},
	buttonblue: class extends self.ISpriteInstance {},
	doorblue: class extends self.ISpriteInstance {},
	ventanadecomandossub: class extends self.ITiledBackgroundInstance {},
	comandoiralasub: class extends self.ISpriteInstance {},
	agregarsub: class extends self.ISpriteInstance {},
	startsub: class extends self.ISpriteInstance {},
	endsub: class extends self.ISpriteInstance {},
	ventanadecomandossubback: class extends self.ITiledBackgroundInstance {},
	selectorprincipal: class extends self.ITiledBackgroundInstance {},
	selectorsub: class extends self.ITiledBackgroundInstance {},
	wintp: class extends self.ISpriteInstance {},
	buttonred: class extends self.ISpriteInstance {},
	doorred: class extends self.ISpriteInstance {},
	doorgreen: class extends self.ISpriteInstance {},
	buttongreen: class extends self.ISpriteInstance {},
	dooryellow: class extends self.ISpriteInstance {},
	buttonyellow: class extends self.ISpriteInstance {},
	copa: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	tutoriales: class extends self.ISpriteInstance {},
	clicktocontinue: class extends self.ISpriteInstance {},
	cursor: class extends self.ISpriteInstance {},
	welcome: class extends self.ISpriteInstance {}
}